apiVersion : apps/v1beta1
kind: Deployment 
metadata: 
  name: k8sdemo 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8sdemo 
    spec:
      containers:
        - name: k8sdemo 
          image: aksacr2registry.azurecr.io/k8sdemo 
          ports:
          - containerPort: 8080